draft | 2020-11-12 22:46:36,326 | 30894 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 22:48:53,729 | 30934 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 22:50:23,975 | 30966 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 22:50:44,263 | 30983 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 22:53:39,028 | 31033 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 22:53:39,233 | 31040 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 22:53:40,010 | 31047 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 22:53:40,536 | 31054 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 22:53:51,302 | 31067 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 23:00:22,695 | 31219 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
draft | 2020-11-12 23:00:40,471 | 31236 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-12 23:02:22,542 | 31272 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-12 23:02:24,456 | 31280 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 13:06:45,549 | 31580 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 13:15:18,934 | 31768 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 13:46:42,400 | 32697 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 13:50:54,960 | 32745 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 13:53:14,252 | 32773 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 13:53:16,563 | 32781 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 16:34:50,215 | 34549 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 19:09:45,799 | 36000 | ERROR | In function divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 19:10:47,933 | 36033 | ERROR | In divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 19:11:42,222 | 36069 | ERROR | In divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
root | 2020-11-13 19:23:38,215 | 36189 | ERROR | In divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
2020-11-14 14:59:43,541 | root | 37200 | ERROR | In divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 6, in divide
    return num1 / num2
ZeroDivisionError: division by zero
2020-11-14 15:00:04,721 | root | 37215 | ERROR | In divide
Traceback (most recent call last):
  File "/Users/humberto/Projects/logger/draft.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/Users/humberto/Projects/logger/other.py", line 8, in divide
    return num1 / num2
ZeroDivisionError: division by zero
